### ISSUE TITLE
对于多账号和推送功能的问题

### ISSUE THREAD

**Issue by wdssfff00** [ZWN2001/big-study-doge-script#1]
目前已经用上了，但是还想帮助同学一起用。所以想了这两项功能。
多账号的个人想法是env方式？然后推送的话可以考虑一些免费的平台，了解了一下有Server、pushplus、企业微信应用这三样。

**Comment by ZWN2001** [comment]
多账号倒是好说，我已经修正参数到了openid列表，直接在list里加参数即可。至于推送，可以自己做，我不太敢把这个放到公开平台服务上，毕竟，额，有点敏感的还是，容易被请去喝茶（挠头）

**Comment by wdssfff00** [comment]
对哦，理解了，感谢

**Comment by ZWN2001** [comment]
（来自一个以前因为跑脚本被辅导员请去喝茶的人的真实感受）（而且标注仅供学习就是为了避免被请去喝茶的）（可以小范围推荐，或者小圈子里推广，但是一旦放到国内公开的地方用那性质可能就不一样了）（github毕竟算是国外的，所以在这里公开其实问题不大）（求生欲拉满了属于是，doge）
